import React, { useState, useEffect } from 'react';
import {
  Box,
  Button,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  Typography,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Chip,
  Grid,
  Alert,
  Snackbar,
  Tabs,
  Tab,
  Switch,
  Tooltip,
  Checkbox,
} from '@mui/material';
import {
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  FilterList as FilterIcon,
  Repeat as RepeatIcon,
  PlayArrow as PlayIcon,
  Pause as PauseIcon,
} from '@mui/icons-material';
import { transactionAPI, recurringTransactionAPI, aiAPI } from '../services/api';

const CATEGORIES = {
  INCOME: ['Lương', 'Thưởng', 'Đầu tư', 'Kinh doanh', 'Thu nhập khác'],
  EXPENSE: ['Ăn uống', 'Di chuyển', 'Giải trí', 'Mua sắm', 'Hóa đơn', 'Y tế', 'Giáo dục', 'Chi phí khác'],
};

const PAYMENT_METHODS = ['Tiền mặt', 'Thẻ tín dụng', 'Chuyển khoản', 'Ví điện tử'];

const RECURRENCE_PATTERNS = {
  DAILY: 'Hàng ngày',
  WEEKLY: 'Hàng tuần',
  MONTHLY: 'Hàng tháng',
  YEARLY: 'Hàng năm',
};

const DAY_OF_WEEK = {
  1: 'Thứ 2',
  2: 'Thứ 3',
  3: 'Thứ 4',
  4: 'Thứ 5',
  5: 'Thứ 6',
  6: 'Thứ 7',
  7: 'Chủ nhật',
};

const Transactions = () => {
  // Tab state
  const [currentTab, setCurrentTab] = useState(0);

  // Regular transactions state
  const [transactions, setTransactions] = useState([]);
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [openDialog, setOpenDialog] = useState(false);
  const [openFilter, setOpenFilter] = useState(false);
  const [editingTransaction, setEditingTransaction] = useState(null);
  const [snackbar, setSnackbar] = useState({ open: false, message: '', severity: 'success' });

  // Recurring transactions state
  const [recurringTransactions, setRecurringTransactions] = useState([]);
  const [recurringPage, setRecurringPage] = useState(0);
  const [recurringRowsPerPage, setRecurringRowsPerPage] = useState(10);
  const [openRecurringDialog, setOpenRecurringDialog] = useState(false);
  const [editingRecurring, setEditingRecurring] = useState(null);

  // AI categorization state
  const [isCategorizing, setIsCategorizing] = useState(false);
  const [categorizationTimeout, setCategorizationTimeout] = useState(null);

  // Auto-generation flag to prevent infinite loop
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Multi-select state for bulk delete
  const [selectedTransactions, setSelectedTransactions] = useState([]);

  const [formData, setFormData] = useState({
    type: 'EXPENSE',
    amount: '',
    category: '',
    description: '',
    transactionDate: new Date().toISOString().split('T')[0],
    paymentMethod: 'Tiền mặt',
    tags: '',
  });

  const [recurringFormData, setRecurringFormData] = useState({
    type: 'EXPENSE',
    amount: '',
    category: '',
    description: '',
    paymentMethod: 'Tiền mặt',
    tags: '',
    recurrencePattern: 'MONTHLY',
    startDate: new Date().toISOString().split('T')[0],
    endDate: '',
    dayOfWeek: 1,
    dayOfMonth: 1,
    monthOfYear: 1,
    isActive: true,
  });

  const [filterData, setFilterData] = useState({
    type: '',
    category: '',
    startDate: '',
    endDate: '',
  });

  useEffect(() => {
    loadTransactions();
    loadRecurringTransactions();
  }, []);

  const loadTransactions = async () => {
    try {
      const response = await transactionAPI.getAll();
      setTransactions(response.data.data || []);
    } catch (error) {
      showSnackbar('Lỗi khi tải giao dịch', 'error');
    }
  };

  const loadRecurringTransactions = async (skipAutoGenerate = false) => {
    try {
      const response = await recurringTransactionAPI.getAll();
      setRecurringTransactions(response.data.data || []);

      // Chỉ tự động tạo 1 lần khi component mount, tránh vòng lặp vô hạn
      if (!skipAutoGenerate && !hasAutoGenerated) {
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        const overdueTransactions = (response.data.data || []).filter(rt => {
          if (!rt.isActive || !rt.nextGenerationDate) return false;
          const nextDate = new Date(rt.nextGenerationDate);
          nextDate.setHours(0, 0, 0, 0);
          return nextDate <= today;
        });

        // Tự động tạo giao dịch cho các transaction quá hạn (chỉ tạo 1 giao dịch/recurring)
        if (overdueTransactions.length > 0) {
          console.log(`Tìm thấy ${overdueTransactions.length} giao dịch định kỳ quá hạn, đang tạo tự động...`);
          setHasAutoGenerated(true); // Đánh dấu đã bắt đầu tạo

          let totalCreated = 0;

          // Với mỗi recurring transaction quá hạn, chỉ tạo 1 giao dịch
          for (const rt of overdueTransactions) {
            try {
              // Tạo 1 giao dịch duy nhất
              await recurringTransactionAPI.generate(rt.id);
              totalCreated++;
              console.log(`Đã tạo giao dịch cho: ${rt.description}`);
            } catch (error) {
              console.error(`Lỗi khi tạo giao dịch tự động cho ${rt.description}:`, error);
            }
          }

          // Reload lại danh sách sau khi tạo xong tất cả
          showSnackbar(`Đã tạo tự động ${totalCreated} giao dịch từ ${overdueTransactions.length} lịch định kỳ`, 'success');

          // Tăng delay lên 1500ms để đảm bảo backend đã cập nhật xong
          setTimeout(async () => {
            await loadRecurringTransactions(true); // Skip auto-generate
            await loadTransactions(); // Reload transactions để hiển thị giao dịch mới

            // Force re-render để cập nhật trạng thái
            setRecurringTransactions(prev => [...prev]);
          }, 1500);
        }
      }
    } catch (error) {
      showSnackbar('Lỗi khi tải giao dịch định kỳ', 'error');
    }
  };

  const handleOpenDialog = (transaction = null) => {
    if (transaction) {
      setEditingTransaction(transaction);
      setFormData({
        type: transaction.type,
        amount: transaction.amount,
        category: transaction.category,
        description: transaction.description || '',
        transactionDate: transaction.transactionDate,
        paymentMethod: transaction.paymentMethod || 'Tiền mặt',
        tags: transaction.tags || '',
      });
    } else {
      setEditingTransaction(null);
      setFormData({
        type: 'EXPENSE',
        amount: '',
        category: '',
        description: '',
        transactionDate: new Date().toISOString().split('T')[0],
        paymentMethod: 'Tiền mặt',
        tags: '',
      });
    }
    setOpenDialog(true);
  };

  const handleCloseDialog = () => {
    setOpenDialog(false);
    setEditingTransaction(null);
  };

  const handleSubmit = async () => {
    try {
      const data = {
        ...formData,
        amount: parseFloat(formData.amount),
      };

      if (editingTransaction) {
        await transactionAPI.update(editingTransaction.id, data);
        showSnackbar('Cập nhật giao dịch thành công!', 'success');
      } else {
        await transactionAPI.create(data);
        showSnackbar('Thêm giao dịch thành công!', 'success');
      }

      handleCloseDialog();
      loadTransactions();
    } catch (error) {
      showSnackbar('Lỗi khi lưu giao dịch', 'error');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Bạn có chắc muốn xóa giao dịch này?')) {
      try {
        await transactionAPI.delete(id);
        showSnackbar('Xóa giao dịch thành công!', 'success');
        loadTransactions();
      } catch (error) {
        showSnackbar('Lỗi khi xóa giao dịch', 'error');
      }
    }
  };

  // Multi-select handlers
  const handleSelectAll = (event) => {
    if (event.target.checked) {
      const allIds = paginatedTransactions.map(t => t.id);
      setSelectedTransactions(allIds);
    } else {
      setSelectedTransactions([]);
    }
  };

  const handleSelectTransaction = (id) => {
    setSelectedTransactions(prev => {
      if (prev.includes(id)) {
        return prev.filter(selectedId => selectedId !== id);
      } else {
        return [...prev, id];
      }
    });
  };

  const handleBulkDelete = async () => {
    if (selectedTransactions.length === 0) {
      showSnackbar('Vui lòng chọn ít nhất 1 giao dịch để xóa', 'warning');
      return;
    }

    if (window.confirm(`Bạn có chắc muốn xóa ${selectedTransactions.length} giao dịch đã chọn?`)) {
      try {
        // Delete all selected transactions
        await Promise.all(
          selectedTransactions.map(id => transactionAPI.delete(id))
        );
        showSnackbar(`Đã xóa thành công ${selectedTransactions.length} giao dịch!`, 'success');
        setSelectedTransactions([]);
        loadTransactions();
      } catch (error) {
        showSnackbar('Lỗi khi xóa giao dịch', 'error');
      }
    }
  };

  const handleFilterApply = async () => {
    try {
      let response;
      if (filterData.startDate && filterData.endDate) {
        response = await transactionAPI.getByDateRange(filterData.startDate, filterData.endDate);
      } else if (filterData.type) {
        response = await transactionAPI.getAll();
        const filtered = response.data.data.filter(t => t.type === filterData.type);
        setTransactions(filtered);
        setOpenFilter(false);
        return;
      } else {
        response = await transactionAPI.getAll();
      }
      setTransactions(response.data.data || []);
      setOpenFilter(false);
    } catch (error) {
      showSnackbar('Lỗi khi lọc giao dịch', 'error');
    }
  };

  const handleFilterReset = () => {
    setFilterData({
      type: '',
      category: '',
      startDate: '',
      endDate: '',
    });
    loadTransactions();
    setOpenFilter(false);
  };

  const showSnackbar = (message, severity = 'success') => {
    setSnackbar({ open: true, message, severity });
  };

  // Helper function để kiểm tra trạng thái tạo giao dịch
  const getGenerationStatus = (recurring) => {
    if (!recurring.isActive) {
      return { label: 'Tạm dừng', color: 'default', icon: null };
    }

    if (!recurring.nextGenerationDate) {
      return { label: 'Chưa có lịch', color: 'default', icon: null };
    }

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const nextDate = new Date(recurring.nextGenerationDate);
    nextDate.setHours(0, 0, 0, 0);

    if (nextDate < today) {
      return { label: 'Quá hạn - Cần tạo', color: 'error', icon: '⚠️' };
    } else if (nextDate.getTime() === today.getTime()) {
      return { label: 'Hôm nay', color: 'warning', icon: '📅' };
    } else {
      return { label: 'Đã tạo', color: 'success', icon: '✓' };
    }
  };

  // AI Auto-categorization for regular transactions
  const handleDescriptionChange = (value, isRecurring = false) => {
    // Update form data
    if (isRecurring) {
      setRecurringFormData({ ...recurringFormData, description: value });
    } else {
      setFormData({ ...formData, description: value });
    }

    // Clear previous timeout
    if (categorizationTimeout) {
      clearTimeout(categorizationTimeout);
    }

    // Only auto-categorize if description is meaningful (at least 3 characters)
    if (value && value.trim().length >= 3) {
      // Debounce: wait 800ms after user stops typing
      const timeout = setTimeout(async () => {
        setIsCategorizing(true);
        try {
          const response = await aiAPI.categorize(value.trim());
          const suggestedCategory = response.data.data.category;

          // Map AI category to our category list
          const categoryMap = {
            'ĂN UỐNG': 'Ăn uống',
            'NHÀ Ở': 'Hóa đơn',
            'GIAO THÔNG': 'Di chuyển',
            'MUA SẮM': 'Mua sắm',
            'GIẢI TRÍ': 'Giải trí',
            'Y TẾ': 'Y tế',
            'GIÁO DỤC': 'Giáo dục',
            'KHÁC': 'Chi phí khác',
          };

          const mappedCategory = categoryMap[suggestedCategory] || suggestedCategory;

          // Check if category exists in current type's categories
          if (isRecurring) {
            const categories = CATEGORIES[recurringFormData.type];
            if (categories.includes(mappedCategory)) {
              setRecurringFormData(prev => ({ ...prev, category: mappedCategory }));
              showSnackbar(`AI gợi ý danh mục: ${mappedCategory}`, 'info');
            }
          } else {
            const categories = CATEGORIES[formData.type];
            if (categories.includes(mappedCategory)) {
              setFormData(prev => ({ ...prev, category: mappedCategory }));
              showSnackbar(`AI gợi ý danh mục: ${mappedCategory}`, 'info');
            }
          }
        } catch (error) {
          console.error('Auto-categorization failed:', error);
          // Silently fail - don't show error to user
        } finally {
          setIsCategorizing(false);
        }
      }, 800);

      setCategorizationTimeout(timeout);
    }
  };

  // Recurring transaction handlers
  const handleOpenRecurringDialog = (recurring = null) => {
    if (recurring) {
      setEditingRecurring(recurring);
      setRecurringFormData({
        type: recurring.type,
        amount: recurring.amount,
        category: recurring.category,
        description: recurring.description || '',
        paymentMethod: recurring.paymentMethod || 'Tiền mặt',
        tags: recurring.tags || '',
        recurrencePattern: recurring.recurrencePattern,
        startDate: recurring.startDate,
        endDate: recurring.endDate || '',
        dayOfWeek: recurring.dayOfWeek || 1,
        dayOfMonth: recurring.dayOfMonth || 1,
        monthOfYear: recurring.monthOfYear || 1,
        isActive: recurring.isActive,
      });
    } else {
      setEditingRecurring(null);
      setRecurringFormData({
        type: 'EXPENSE',
        amount: '',
        category: '',
        description: '',
        paymentMethod: 'Tiền mặt',
        tags: '',
        recurrencePattern: 'MONTHLY',
        startDate: new Date().toISOString().split('T')[0],
        endDate: '',
        dayOfWeek: 1,
        dayOfMonth: 1,
        monthOfYear: 1,
        isActive: true,
      });
    }
    setOpenRecurringDialog(true);
  };

  const handleCloseRecurringDialog = () => {
    setOpenRecurringDialog(false);
    setEditingRecurring(null);
  };

  const handleRecurringSubmit = async () => {
    try {
      const data = {
        ...recurringFormData,
        amount: parseFloat(recurringFormData.amount),
      };

      if (editingRecurring) {
        await recurringTransactionAPI.update(editingRecurring.id, data);
        showSnackbar('Cập nhật giao dịch định kỳ thành công!', 'success');
      } else {
        await recurringTransactionAPI.create(data);
        showSnackbar('Thêm giao dịch định kỳ thành công!', 'success');
      }

      handleCloseRecurringDialog();
      loadRecurringTransactions();
    } catch (error) {
      showSnackbar('Lỗi khi lưu giao dịch định kỳ', 'error');
    }
  };

  const handleRecurringDelete = async (id) => {
    if (window.confirm('Bạn có chắc muốn xóa giao dịch định kỳ này?')) {
      try {
        await recurringTransactionAPI.delete(id);
        showSnackbar('Xóa giao dịch định kỳ thành công!', 'success');
        loadRecurringTransactions();
      } catch (error) {
        showSnackbar('Lỗi khi xóa giao dịch định kỳ', 'error');
      }
    }
  };

  const handleRecurringToggle = async (id) => {
    try {
      await recurringTransactionAPI.toggle(id);
      showSnackbar('Đã cập nhật trạng thái giao dịch định kỳ!', 'success');
      loadRecurringTransactions();
    } catch (error) {
      showSnackbar('Lỗi khi cập nhật trạng thái', 'error');
    }
  };

  const handleRecurringGenerate = async (id) => {
    try {
      await recurringTransactionAPI.generate(id);
      showSnackbar('Đã tạo giao dịch từ mẫu định kỳ!', 'success');
      loadTransactions();
    } catch (error) {
      showSnackbar('Lỗi khi tạo giao dịch', 'error');
    }
  };

  const handleChangePage = (event, newPage) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  const handleRecurringChangePage = (event, newPage) => {
    setRecurringPage(newPage);
  };

  const handleRecurringChangeRowsPerPage = (event) => {
    setRecurringRowsPerPage(parseInt(event.target.value, 10));
    setRecurringPage(0);
  };

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('vi-VN', {
      style: 'currency',
      currency: 'VND',
    }).format(amount); // Hiển thị số tiền thực tế không nhân 1000
  };

  const paginatedTransactions = transactions.slice(
    page * rowsPerPage,
    page * rowsPerPage + rowsPerPage
  );

  const paginatedRecurringTransactions = recurringTransactions.slice(
    recurringPage * recurringRowsPerPage,
    recurringPage * recurringRowsPerPage + recurringRowsPerPage
  );

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4">Quản Lý Giao Dịch</Typography>
      </Box>

      <Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 3 }}>
        <Tabs value={currentTab} onChange={(e, newValue) => setCurrentTab(newValue)}>
          <Tab label="Giao Dịch Thông Thường" />
          <Tab label="Giao Dịch Định Kỳ" icon={<RepeatIcon />} iconPosition="end" />
        </Tabs>
      </Box>

      {currentTab === 0 && (
        <Box>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
            <Box>
              {selectedTransactions.length > 0 && (
                <Button
                  variant="contained"
                  color="error"
                  startIcon={<DeleteIcon />}
                  onClick={handleBulkDelete}
                >
                  Xóa đã chọn ({selectedTransactions.length})
                </Button>
              )}
            </Box>
            <Box>
              <Button
                variant="outlined"
                startIcon={<FilterIcon />}
                onClick={() => setOpenFilter(true)}
                sx={{ mr: 2 }}
              >
                Lọc
              </Button>
              <Button
                variant="contained"
                startIcon={<AddIcon />}
                onClick={() => handleOpenDialog()}
              >
                Thêm Giao Dịch
              </Button>
            </Box>
          </Box>

      <TableContainer component={Paper}>
        <Table>
          <TableHead>
            <TableRow sx={{ backgroundColor: '#f5f5f5' }}>
              <TableCell padding="checkbox">
                <Checkbox
                  indeterminate={selectedTransactions.length > 0 && selectedTransactions.length < paginatedTransactions.length}
                  checked={paginatedTransactions.length > 0 && selectedTransactions.length === paginatedTransactions.length}
                  onChange={handleSelectAll}
                />
              </TableCell>
              <TableCell><strong>Ngày</strong></TableCell>
              <TableCell><strong>Loại</strong></TableCell>
              <TableCell><strong>Danh Mục</strong></TableCell>
              <TableCell><strong>Mô Tả</strong></TableCell>
              <TableCell align="right"><strong>Số Tiền</strong></TableCell>
              <TableCell><strong>Phương Thức</strong></TableCell>
              <TableCell align="center"><strong>Thao Tác</strong></TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {paginatedTransactions.length === 0 ? (
              <TableRow>
                <TableCell colSpan={8} align="center">
                  <Typography variant="body2" color="text.secondary">
                    Chưa có giao dịch nào. Hãy thêm giao dịch đầu tiên!
                  </Typography>
                </TableCell>
              </TableRow>
            ) : (
              paginatedTransactions.map((transaction) => (
                <TableRow key={transaction.id} hover>
                  <TableCell padding="checkbox">
                    <Checkbox
                      checked={selectedTransactions.includes(transaction.id)}
                      onChange={() => handleSelectTransaction(transaction.id)}
                    />
                  </TableCell>
                  <TableCell>{new Date(transaction.transactionDate).toLocaleDateString('vi-VN')}</TableCell>
                  <TableCell>
                    <Chip
                      label={transaction.type === 'INCOME' ? 'Thu Nhập' : 'Chi Tiêu'}
                      color={transaction.type === 'INCOME' ? 'success' : 'error'}
                      size="small"
                    />
                  </TableCell>
                  <TableCell>{transaction.category}</TableCell>
                  <TableCell>{transaction.description || '-'}</TableCell>
                  <TableCell align="right">
                    <Typography
                      variant="body2"
                      sx={{
                        color: transaction.type === 'INCOME' ? 'success.main' : 'error.main',
                        fontWeight: 'bold',
                      }}
                    >
                      {transaction.type === 'INCOME' ? '+' : '-'}{formatCurrency(transaction.amount)}
                    </Typography>
                  </TableCell>
                  <TableCell>{transaction.paymentMethod}</TableCell>
                  <TableCell align="center">
                    <IconButton
                      size="small"
                      color="primary"
                      onClick={() => handleOpenDialog(transaction)}
                    >
                      <EditIcon fontSize="small" />
                    </IconButton>
                    <IconButton
                      size="small"
                      color="error"
                      onClick={() => handleDelete(transaction.id)}
                    >
                      <DeleteIcon fontSize="small" />
                    </IconButton>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
        <TablePagination
          component="div"
          count={transactions.length}
          page={page}
          onPageChange={handleChangePage}
          rowsPerPage={rowsPerPage}
          onRowsPerPageChange={handleChangeRowsPerPage}
          labelRowsPerPage="Số dòng mỗi trang:"
          labelDisplayedRows={({ from, to, count }) => `${from}-${to} trong tổng ${count}`}
        />
      </TableContainer>

      {/* Dialog Thêm/Sửa Giao Dịch */}
      <Dialog open={openDialog} onClose={handleCloseDialog} maxWidth="sm" fullWidth>
        <DialogTitle>
          {editingTransaction ? 'Chỉnh Sửa Giao Dịch' : 'Thêm Giao Dịch Mới'}
        </DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12}>
              <FormControl fullWidth>
                <InputLabel>Loại Giao Dịch</InputLabel>
                <Select
                  value={formData.type}
                  label="Loại Giao Dịch"
                  onChange={(e) => setFormData({ ...formData, type: e.target.value, category: '' })}
                >
                  <MenuItem value="INCOME">Thu Nhập</MenuItem>
                  <MenuItem value="EXPENSE">Chi Tiêu</MenuItem>
                </Select>
              </FormControl>
            </Grid>

            <Grid item xs={12}>
              <FormControl fullWidth>
                <InputLabel>Danh Mục</InputLabel>
                <Select
                  value={formData.category}
                  label="Danh Mục"
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                >
                  {CATEGORIES[formData.type].map((cat) => (
                    <MenuItem key={cat} value={cat}>{cat}</MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Số Tiền"
                type="number"
                value={formData.amount}
                onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                InputProps={{
                  inputProps: { min: 0, step: 0.01 }
                }}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Ngày Giao Dịch"
                type="date"
                value={formData.transactionDate}
                onChange={(e) => setFormData({ ...formData, transactionDate: e.target.value })}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>

            <Grid item xs={12}>
              <FormControl fullWidth>
                <InputLabel>Phương Thức Thanh Toán</InputLabel>
                <Select
                  value={formData.paymentMethod}
                  label="Phương Thức Thanh Toán"
                  onChange={(e) => setFormData({ ...formData, paymentMethod: e.target.value })}
                >
                  {PAYMENT_METHODS.map((method) => (
                    <MenuItem key={method} value={method}>{method}</MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Mô Tả"
                multiline
                rows={2}
                value={formData.description}
                onChange={(e) => handleDescriptionChange(e.target.value, false)}
                helperText={isCategorizing ? "🤖 AI đang phân tích..." : "Nhập mô tả để AI tự động gợi ý danh mục"}
              />
            </Grid>

            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Tags (phân cách bằng dấu phẩy)"
                value={formData.tags}
                onChange={(e) => setFormData({ ...formData, tags: e.target.value })}
                placeholder="VD: ăn trưa, công việc"
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDialog}>Hủy</Button>
          <Button
            variant="contained"
            onClick={handleSubmit}
            disabled={!formData.amount || !formData.category}
          >
            {editingTransaction ? 'Cập Nhật' : 'Thêm'}
          </Button>
        </DialogActions>
      </Dialog>

        {/* Dialog Lọc */}
        <Dialog open={openFilter} onClose={() => setOpenFilter(false)} maxWidth="sm" fullWidth>
          <DialogTitle>Lọc Giao Dịch</DialogTitle>
          <DialogContent>
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid item xs={12}>
                <FormControl fullWidth>
                  <InputLabel>Loại Giao Dịch</InputLabel>
                  <Select
                    value={filterData.type}
                    label="Loại Giao Dịch"
                    onChange={(e) => setFilterData({ ...filterData, type: e.target.value })}
                  >
                    <MenuItem value="">Tất cả</MenuItem>
                    <MenuItem value="INCOME">Thu Nhập</MenuItem>
                    <MenuItem value="EXPENSE">Chi Tiêu</MenuItem>
                  </Select>
                </FormControl>
              </Grid>

              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Từ Ngày"
                  type="date"
                  value={filterData.startDate}
                  onChange={(e) => setFilterData({ ...filterData, startDate: e.target.value })}
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>

              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Đến Ngày"
                  type="date"
                  value={filterData.endDate}
                  onChange={(e) => setFilterData({ ...filterData, endDate: e.target.value })}
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>
            </Grid>
          </DialogContent>
          <DialogActions>
            <Button onClick={handleFilterReset}>Đặt Lại</Button>
            <Button onClick={() => setOpenFilter(false)}>Hủy</Button>
            <Button variant="contained" onClick={handleFilterApply}>
              Áp Dụng
            </Button>
          </DialogActions>
        </Dialog>
        </Box>
      )}

      {/* Tab 2: Recurring Transactions */}
      {currentTab === 1 && (
        <Box>
          <Box sx={{ display: 'flex', justifyContent: 'flex-end', mb: 2 }}>
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => handleOpenRecurringDialog()}
            >
              Thêm Giao Dịch Định Kỳ
            </Button>
          </Box>

          <TableContainer component={Paper}>
            <Table>
              <TableHead>
                <TableRow sx={{ backgroundColor: '#f5f5f5' }}>
                  <TableCell><strong>Loại</strong></TableCell>
                  <TableCell><strong>Danh Mục</strong></TableCell>
                  <TableCell><strong>Mô Tả</strong></TableCell>
                  <TableCell align="right"><strong>Số Tiền</strong></TableCell>
                  <TableCell><strong>Chu Kỳ</strong></TableCell>
                  <TableCell><strong>Ngày Tiếp Theo</strong></TableCell>
                  <TableCell align="center"><strong>Trạng Thái Tạo</strong></TableCell>
                  <TableCell align="center"><strong>Hoạt Động</strong></TableCell>
                  <TableCell align="center"><strong>Thao Tác</strong></TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {paginatedRecurringTransactions.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={9} align="center">
                      <Typography variant="body2" color="text.secondary">
                        Chưa có giao dịch định kỳ nào. Hãy thêm giao dịch định kỳ đầu tiên!
                      </Typography>
                    </TableCell>
                  </TableRow>
                ) : (
                  paginatedRecurringTransactions.map((recurring) => (
                    <TableRow key={recurring.id} hover>
                      <TableCell>
                        <Chip
                          label={recurring.type === 'INCOME' ? 'Thu Nhập' : 'Chi Tiêu'}
                          color={recurring.type === 'INCOME' ? 'success' : 'error'}
                          size="small"
                        />
                      </TableCell>
                      <TableCell>{recurring.category}</TableCell>
                      <TableCell>{recurring.description || '-'}</TableCell>
                      <TableCell align="right">
                        <Typography
                          variant="body2"
                          sx={{
                            color: recurring.type === 'INCOME' ? 'success.main' : 'error.main',
                            fontWeight: 'bold',
                          }}
                        >
                          {formatCurrency(recurring.amount)}
                        </Typography>
                      </TableCell>
                      <TableCell>
                        <Chip
                          label={RECURRENCE_PATTERNS[recurring.recurrencePattern]}
                          size="small"
                          variant="outlined"
                        />
                      </TableCell>
                      <TableCell>
                        {recurring.nextGenerationDate ?
                          new Date(recurring.nextGenerationDate).toLocaleDateString('vi-VN') : '-'}
                      </TableCell>
                      <TableCell align="center">
                        {(() => {
                          const status = getGenerationStatus(recurring);
                          return (
                            <Chip
                              label={`${status.icon || ''} ${status.label}`}
                              color={status.color}
                              size="small"
                              variant={status.color === 'error' ? 'filled' : 'outlined'}
                            />
                          );
                        })()}
                      </TableCell>
                      <TableCell align="center">
                        <Chip
                          label={recurring.isActive ? 'Hoạt động' : 'Tạm dừng'}
                          color={recurring.isActive ? 'success' : 'default'}
                          size="small"
                        />
                      </TableCell>
                      <TableCell align="center">
                        <Tooltip title={recurring.isActive ? 'Tạm dừng' : 'Kích hoạt'}>
                          <IconButton
                            size="small"
                            color={recurring.isActive ? 'warning' : 'success'}
                            onClick={() => handleRecurringToggle(recurring.id)}
                          >
                            {recurring.isActive ? <PauseIcon fontSize="small" /> : <PlayIcon fontSize="small" />}
                          </IconButton>
                        </Tooltip>
                        <Tooltip title="Tạo giao dịch ngay">
                          <IconButton
                            size="small"
                            color="info"
                            onClick={() => handleRecurringGenerate(recurring.id)}
                          >
                            <RepeatIcon fontSize="small" />
                          </IconButton>
                        </Tooltip>
                        <IconButton
                          size="small"
                          color="primary"
                          onClick={() => handleOpenRecurringDialog(recurring)}
                        >
                          <EditIcon fontSize="small" />
                        </IconButton>
                        <IconButton
                          size="small"
                          color="error"
                          onClick={() => handleRecurringDelete(recurring.id)}
                        >
                          <DeleteIcon fontSize="small" />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
            <TablePagination
              component="div"
              count={recurringTransactions.length}
              page={recurringPage}
              onPageChange={handleRecurringChangePage}
              rowsPerPage={recurringRowsPerPage}
              onRowsPerPageChange={handleRecurringChangeRowsPerPage}
              labelRowsPerPage="Số dòng mỗi trang:"
              labelDisplayedRows={({ from, to, count }) => `${from}-${to} trong tổng ${count}`}
            />
          </TableContainer>
        </Box>
      )}

      {/* Dialog Thêm/Sửa Giao Dịch Định Kỳ */}
      <Dialog open={openRecurringDialog} onClose={handleCloseRecurringDialog} maxWidth="md" fullWidth>
        <DialogTitle>
          {editingRecurring ? 'Chỉnh Sửa Giao Dịch Định Kỳ' : 'Thêm Giao Dịch Định Kỳ'}
        </DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12} sm={6}>
              <FormControl fullWidth>
                <InputLabel>Loại Giao Dịch</InputLabel>
                <Select
                  value={recurringFormData.type}
                  label="Loại Giao Dịch"
                  onChange={(e) => setRecurringFormData({ ...recurringFormData, type: e.target.value, category: '' })}
                >
                  <MenuItem value="INCOME">Thu Nhập</MenuItem>
                  <MenuItem value="EXPENSE">Chi Tiêu</MenuItem>
                </Select>
              </FormControl>
            </Grid>

            <Grid item xs={12} sm={6}>
              <FormControl fullWidth>
                <InputLabel>Danh Mục</InputLabel>
                <Select
                  value={recurringFormData.category}
                  label="Danh Mục"
                  onChange={(e) => setRecurringFormData({ ...recurringFormData, category: e.target.value })}
                >
                  {CATEGORIES[recurringFormData.type].map((cat) => (
                    <MenuItem key={cat} value={cat}>{cat}</MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Số Tiền"
                type="number"
                value={recurringFormData.amount}
                onChange={(e) => setRecurringFormData({ ...recurringFormData, amount: e.target.value })}
                InputProps={{
                  inputProps: { min: 0, step: 0.01 }
                }}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <FormControl fullWidth>
                <InputLabel>Phương Thức Thanh Toán</InputLabel>
                <Select
                  value={recurringFormData.paymentMethod}
                  label="Phương Thức Thanh Toán"
                  onChange={(e) => setRecurringFormData({ ...recurringFormData, paymentMethod: e.target.value })}
                >
                  {PAYMENT_METHODS.map((method) => (
                    <MenuItem key={method} value={method}>{method}</MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Mô Tả"
                multiline
                rows={2}
                value={recurringFormData.description}
                onChange={(e) => handleDescriptionChange(e.target.value, true)}
                helperText={isCategorizing ? "🤖 AI đang phân tích..." : "Nhập mô tả để AI tự động gợi ý danh mục"}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <FormControl fullWidth>
                <InputLabel>Chu Kỳ Lặp Lại</InputLabel>
                <Select
                  value={recurringFormData.recurrencePattern}
                  label="Chu Kỳ Lặp Lại"
                  onChange={(e) => setRecurringFormData({ ...recurringFormData, recurrencePattern: e.target.value })}
                >
                  {Object.entries(RECURRENCE_PATTERNS).map(([key, value]) => (
                    <MenuItem key={key} value={key}>{value}</MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            {recurringFormData.recurrencePattern === 'WEEKLY' && (
              <Grid item xs={12} sm={6}>
                <FormControl fullWidth>
                  <InputLabel>Ngày Trong Tuần</InputLabel>
                  <Select
                    value={recurringFormData.dayOfWeek}
                    label="Ngày Trong Tuần"
                    onChange={(e) => setRecurringFormData({ ...recurringFormData, dayOfWeek: e.target.value })}
                  >
                    {Object.entries(DAY_OF_WEEK).map(([key, value]) => (
                      <MenuItem key={key} value={parseInt(key)}>{value}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
            )}

            {recurringFormData.recurrencePattern === 'MONTHLY' && (
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Ngày Trong Tháng"
                  type="number"
                  value={recurringFormData.dayOfMonth}
                  onChange={(e) => setRecurringFormData({ ...recurringFormData, dayOfMonth: parseInt(e.target.value) })}
                  InputProps={{
                    inputProps: { min: 1, max: 31 }
                  }}
                  helperText="Nhập số từ 1-31"
                />
              </Grid>
            )}

            {recurringFormData.recurrencePattern === 'YEARLY' && (
              <>
                <Grid item xs={12} sm={3}>
                  <TextField
                    fullWidth
                    label="Ngày"
                    type="number"
                    value={recurringFormData.dayOfMonth}
                    onChange={(e) => setRecurringFormData({ ...recurringFormData, dayOfMonth: parseInt(e.target.value) })}
                    InputProps={{
                      inputProps: { min: 1, max: 31 }
                    }}
                  />
                </Grid>
                <Grid item xs={12} sm={3}>
                  <TextField
                    fullWidth
                    label="Tháng"
                    type="number"
                    value={recurringFormData.monthOfYear}
                    onChange={(e) => setRecurringFormData({ ...recurringFormData, monthOfYear: parseInt(e.target.value) })}
                    InputProps={{
                      inputProps: { min: 1, max: 12 }
                    }}
                  />
                </Grid>
              </>
            )}

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Ngày Bắt Đầu"
                type="date"
                value={recurringFormData.startDate}
                onChange={(e) => setRecurringFormData({ ...recurringFormData, startDate: e.target.value })}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Ngày Kết Thúc (Tùy chọn)"
                type="date"
                value={recurringFormData.endDate}
                onChange={(e) => setRecurringFormData({ ...recurringFormData, endDate: e.target.value })}
                InputLabelProps={{ shrink: true }}
                helperText="Để trống nếu không có ngày kết thúc"
              />
            </Grid>

            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Tags (phân cách bằng dấu phẩy)"
                value={recurringFormData.tags}
                onChange={(e) => setRecurringFormData({ ...recurringFormData, tags: e.target.value })}
                placeholder="VD: tiền nhà, hàng tháng"
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseRecurringDialog}>Hủy</Button>
          <Button
            variant="contained"
            onClick={handleRecurringSubmit}
            disabled={!recurringFormData.amount || !recurringFormData.category}
          >
            {editingRecurring ? 'Cập Nhật' : 'Thêm'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Snackbar Thông Báo */}
      <Snackbar
        open={snackbar.open}
        autoHideDuration={3000}
        onClose={() => setSnackbar({ ...snackbar, open: false })}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert
          onClose={() => setSnackbar({ ...snackbar, open: false })}
          severity={snackbar.severity}
          sx={{ width: '100%' }}
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default Transactions;
